# .ruff.toml — lint-hotfix-v1
[ruff]
line-length = 100
src = ["ingest", "ingest_worker", "lib", "snp_enrichment_system"]
extend-exclude = [
  "risk_reports/out",
  "metabase_data",
  ".ruff_cache",
  "build",
  "dist",
  ".venv",
  "venv",
  ".git"
]
force-exclude = true

[lint]
select = ["E", "F", "W", "I", "UP"]
ignore = []

[lint.per-file-ignores]
"**/__init__.py" = ["F401"]  # allow explicit re-exports

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
