# Ruff configuration
line-length = 100
target-version = "py311"
extend-exclude = ["db_data", "metabase_data", ".venv*", ".git", ".*_data"]

[lint]
# E/F: pycodestyle/pyflakes, I: import sorting
select = ["E", "F", "I"]
ignore = ["E501"]

[lint.isort]
known-first-party = ["ingest", "ingest_worker"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
