services:
  ingest-worker:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file: .env
    depends_on: [ db ]
    volumes:
      - /mnt/nas_storage/vep/cache:/vep/cache:ro
      - /mnt/nas_storage/vep/reference:/vep/reference:ro
    healthcheck:
      test: ["CMD","python","-c","print('ok')"]
      interval: 30s
      timeout: 5s
      retries: 3
