name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { python-version: ["3.11","3.12"] }
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: genomics
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s
          --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python-version }} }
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt','pyproject.toml') }}
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt ruff black mypy pytest || pip install ruff black mypy pytest
      - run: ruff check .
      - run: ruff format --check .
      - run: black --check .
      - run: mypy ingest ingest_worker lib scripts snp_enrichment_system || true
      - run: pytest
