[tool.black]
line-length = 100
target-version = ["py311","py312"]

[tool.ruff]
line-length = 100
extend-exclude = [".venv","metabase_data","risk_reports","db_data",".genomics_patches"]
select = ["E","F","I","UP","B","SIM","W"]
ignore = ["E203","W503"]

[tool.ruff.lint.isort]
known-first-party = ["lib","ingest","ingest_worker","snp_enrichment_system","scripts"]

[tool.ruff.format]
quote-style = "double"
